# Generated by Django 4.2 on 2023-04-15 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=1)),
                ('is_spectator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255, unique=True)),
                ('current_round_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('text', 'Text'), ('drawing', 'Drawing'), ('emoji', 'Emoji')], max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_in_seconds', models.IntegerField()),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.prompt')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('format', models.CharField(choices=[('text', 'Text'), ('drawing', 'Drawing'), ('emoji', 'Emoji')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('preceding_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.prompt')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.round')),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='preceding_response',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='game.response'),
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name', 'room'), name='unique_spectator_name_in_room'),
        ),
    ]
