# Generated by Django 4.2 on 2023-04-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dramatic_reading_round',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='drawing_round',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='one_sentence_story_round',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='poem_round',
            field=models.BooleanField(null=True),
        ),
    ]
