# Generated by Django 4.2 on 2023-05-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_room_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='unique_spectator_name_in_room',
        ),
        migrations.AlterField(
            model_name='room',
            name='current_round_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('name', 'room'), name='unique_player_name_in_room'),
        ),
    ]
